import btoa from 'btoa'

interface Role {
  email: string
}

export const role0 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role0@test.com',
}

export const role1 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role1@test.com',
}

export const role2 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role2@test.com',
}
export const role2OnAir1 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role2OnAir1@test.com',
}

export const role3OnAir1 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role3OnAir1@test.com',
}

export const role3 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role3@test.com',
}

export const role4 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role4@test.com',
}

const role5 = {
  exp: 1602735212,
  iat: 1602734312,
  auth_time: 1602731339,
  jti: '######-####-####',
  iss: 'https://login.dsop.io/auth/realms/baby-yoda',
  sub: '######-####-####',
  typ: 'Bearer',
  azp: 'platform1_a8604cc9-f5e9-4656-802d-d05624370245_hello-world-authservice',
  nonce: '###################',
  session_state: '######-####-####',
  acr: '0',
  scope: '#### ######',
  'group-simple': ['#########', '#######', '####'],
  preferred_username: 'real-john-doe',
  given_name: 'Bob',
  activecac: '',
  affiliation: 'US Air Force',
  'group-full': [
    '##########/########/#########',
    '##########/########/#######',
    '##########/########/####',
  ],
  organization: 'Platform One',
  name: 'Bob Dylan',
  nickname: 'Cool Nickname',
  usercertificate: '##################',
  rank: 'A1C',
  position: 'Peasant',
  family_name: 'Dylan',
  email: 'role5@test.com',
}

export function fakeWrapper(role:Role):string  { return 'Bearer fakestuff.' + btoa(JSON.stringify(role)); }
export const role0e = fakeWrapper(role0) 
export const role1e = fakeWrapper(role1) 
export const role2e = fakeWrapper(role2) 
export const role3e = fakeWrapper(role3) 
export const role4e = fakeWrapper(role4) 
export const role5e = fakeWrapper(role5) 
export const role3OnAir1e = fakeWrapper(role3OnAir1)
export const role2OnAir1e = fakeWrapper(role2OnAir1)

export const oldDate = new Date('03/08/1980');

export const lastModifiedInfo = {    
    lastModified: oldDate,
    lastModifiedBy: "bogus"
  }
