###
GET http://localhost:8080/fl-api/cargo?aircraftid=1
###
PUT http://localhost:8080/fl-api/cargo
content-type: application/json

{
  "cargoid": 0,
  "aircraftid": 2,
  "name": "create",
  "weight": 120,
  "fs": 300
}
###
PUT http://localhost:8080/fl-api/cargo
content-type: application/json

{
  "cargoid": 4,
  "aircraftid": 2,
  "name": "update",
  "weight": 120,
  "fs": 300
}
###
DELETE http://localhost:8080/fl-api/cargo?cargoid=4