###
GET http://localhost:8080/fl-api/config?aircraftId=2
###
PUT http://localhost:8080/fl-api/config
content-type: application/json

{
  "configId": 0,
  "aircraftId": 2,
  "name": "create"
}
###
PUT http://localhost:8080/fl-api/config
content-type: application/json

{
  "configId": 39,
  "aircraftId": 2,
  "name": "update"
}
###
DELETE http://localhost:8080/fl-api/config?configId=39