###
GET http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "aircraftid": 1,
  "configid": 1,
  "name": "stuff"
}
###
PUT http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "aircraftid": 1,
  "configid": 1,
  "cargoid": 10,
  "configcargoid": 0,
  "fs": 4000,
  "qty": 2
}
###
PUT http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "aircraftid": 1,
  "configid": 1,
  "cargoid": 10,
  "configcargoid": 860,
  "fs": 400,
  "qty": 1
}
###
DELETE http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "configcargoid": 860
}