###
GET http://localhost:8080/fl-api/configcargo?configId=1
###
PUT http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "aircraftId": 1,
  "configId": 1,
  "cargoid": 10,
  "configcargoid": 0,
  "fs": 4000,
  "qty": 2
}
###
PUT http://localhost:8080/fl-api/configcargo
content-type: application/json

{
  "aircraftId": 1,
  "configId": 1,
  "cargoid": 10,
  "configcargoid": 860,
  "fs": 400,
  "qty": 1
}
###
DELETE http://localhost:8080/fl-api/configcargo?configcargoid=860