###
GET http://localhost:8080/fl-api/glossary?aircraftId=2
###
PUT http://localhost:8080/fl-api/glossary
content-type: application/json

{
  "glossaryId": 0,
  "aircraftId": 2,
  "name": "create",
  "body": "body"
}
###
PUT http://localhost:8080/fl-api/glossary
content-type: application/json

{
  "glossaryId": 19,
  "aircraftId": 2,
  "name": "update",
  "body": "body"
}
###
DELETE http://localhost:8080/fl-api/glossary?"glossaryId=19