###
GET http://localhost:8080/fl-api/tank?aircraftId=1
###
PUT http://localhost:8080/fl-api/tank
content-type: application/json

{
  "aircraftId": 1,
  "tankId": 0,
  "name": "create",
  "weightsCSV": "2,4,6",
  "simpleMomsCSV": "1,2,3"
}
###
PUT http://localhost:8080/fl-api/tank
content-type: application/json

{
  "aircraftId": 1,
  "tankId": 9,
  "name": "update",
  "weightsCSV": "2,4,6",
  "simpleMomsCSV": "1,2,3"
}
###
DELETE http://localhost:8080/fl-api/tank?tankId=9