###
GET http://localhost:8080/fl-api/user?aircraftId=1
###
GET http://localhost:8080/fl-api/user
###
PUT http://localhost:8080/fl-api/user
content-type: application/json

{
  "userId": 0,
  "aircraftId": 1,
  "name": "create",
  "role": 1
}
###
PUT http://localhost:8080/fl-api/user
content-type: application/json

{
  "userId": 17,
  "aircraftId": 1,
  "name": "update",
  "role": 2
}
###
DELETE http://localhost:8080/fl-api/user?userId=17