###
GET http://localhost:8080/fl-api/user
content-type: application/json

{
  "aircraftid": 1
}
###
GET http://localhost:8080/fl-api/user
###
PUT http://localhost:8080/fl-api/user
content-type: application/json

{
  "userid": 0,
  "aircraftid": 1,
  "email": "create",
  "role": 1
}
###
PUT http://localhost:8080/fl-api/user
content-type: application/json

{
  "userid": 17,
  "aircraftid": 1,
  "email": "update",
  "role": 2
}
###
DELETE http://localhost:8080/fl-api/user
content-type: application/json

{
  "userid": 17
}